field.field_settings.[FIELD ID]:
  type: mapping
  label: 'RandomName settings'
  mapping:
    size:
      type: string
      label: 'Size'

field.formatter.settings.[FORMATTER ID]:
  type: mapping
  label: 'FORMATTER NAME text length'
  mapping:
    text_length:
      type: string
      label: 'Text Length'

field.widget.settings.[WIDGET ID]:
  type: mapping
  label: 'WIDGET NAME widget settings'
  mapping:
    size:
      type: integer
      label: 'Size'
